server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://ecommerce-postgres:5432/ecommerce
    username: postgres
    password: postgres
    hikari:
      initializationFailTimeout: 60000
      connectionTimeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: payment_schema
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        session.timeout.ms: 30000

management:
  endpoints:
    web:
      exposure:
        include: health